// src/lib/components/PriceChart.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { createChart, AreaSeries, LineSeries } from 'lightweight-charts';
  import type { IChartApi } from 'lightweight-charts';

  interface Props {
    marketId: string;
  }

  let { marketId }: Props = $props();

  interface PricePoint {
    timestamp: number;
    yes_price: number;
    no_price: number;
  }

  let container = $state<HTMLDivElement | undefined>(undefined);
  let chart: IChartApi | null = null;
  let empty = $state(false);

  async function fetchPriceHistory(): Promise<PricePoint[]> {
    try {
      const res = await fetch(`/api/market/${marketId}/price-history`);
      if (!res.ok) return [];
      return await res.json();
    } catch {
      return [];
    }
  }

  onMount(async () => {
    if (!container) return;

    const data = await fetchPriceHistory();

    if (data.length === 0) {
      empty = true;
      return;
    }

    chart = createChart(container, {
      layout: {
        background: { color: '#0a0a0a' },
        textColor: '#737373',
      },
      grid: {
        vertLines: { color: '#1a1a1a' },
        horzLines: { color: '#1a1a1a' },
      },
      crosshair: {
        vertLine: { color: '#404040' },
        horzLine: { color: '#404040' },
      },
      rightPriceScale: {
        borderColor: '#262626',
      },
      timeScale: {
        borderColor: '#262626',
        timeVisible: true,
      },
      width: container.clientWidth,
      height: 280,
    });

    const yesSeries = chart.addSeries(AreaSeries, {
      lineColor: '#10b981',
      topColor: 'rgba(16, 185, 129, 0.2)',
      bottomColor: 'rgba(16, 185, 129, 0)',
      lineWidth: 2,
      priceFormat: { type: 'price', precision: 3, minMove: 0.001 },
    });

    const noSeries = chart.addSeries(LineSeries, {
      color: '#f43f5e',
      lineWidth: 1,
      priceFormat: { type: 'price', precision: 3, minMove: 0.001 },
    });

    const yesData = data.map((p) => ({ time: p.timestamp as any, value: p.yes_price }));
    const noData = data.map((p) => ({ time: p.timestamp as any, value: p.no_price }));

    yesSeries.setData(yesData);
    noSeries.setData(noData);

    chart.timeScale().fitContent();

    const ro = new ResizeObserver(() => {
      if (chart && container) {
        chart.resize(container.clientWidth, 280);
      }
    });
    ro.observe(container);

    return () => ro.disconnect();
  });

  onDestroy(() => {
    chart?.remove();
    chart = null;
  });
</script>

<div class="w-full">
  {#if empty}
    <div class="flex items-center justify-center h-[280px] text-neutral-600 text-sm">
      No price history yet
    </div>
  {:else}
    <div bind:this={container} class="w-full h-[280px]"></div>
  {/if}
</div>

// src/PriceChart.tsx
import { useEffect, useRef } from 'react'
import {
  createChart,
  AreaSeries,
  LineSeries,
  ColorType,
  type IChartApi,
  type ISeriesApi,
  type UTCTimestamp,
} from 'lightweight-charts'

export type HistoryPoint = {
  time: number
  priceLong: number
  reserve: number
}

type Props = {
  data: HistoryPoint[]
}

function formatAsPercent(value: number) {
  return `${(value * 100).toFixed(1)}%`
}

function formatAsSats(value: number) {
  return `$${value.toFixed(0)}`
}

export default function PriceChart({ data }: Props) {
  const containerRef = useRef<HTMLDivElement>(null)
  const chartRef = useRef<IChartApi | null>(null)
  const priceSeriesRef = useRef<ISeriesApi<'Area'> | null>(null)
  const reserveSeriesRef = useRef<ISeriesApi<'Line'> | null>(null)

  useEffect(() => {
    const container = containerRef.current
    if (!container) return

    const chart = createChart(container, {
      width: container.clientWidth,
      height: 160,
      layout: {
        background: { type: ColorType.Solid, color: 'transparent' },
        textColor: 'rgba(255, 255, 255, 0.4)',
        fontSize: 10,
      },
      grid: {
        vertLines: { color: 'rgba(255, 255, 255, 0.04)' },
        horzLines: { color: 'rgba(255, 255, 255, 0.04)' },
      },
      leftPriceScale: {
        visible: true,
        borderVisible: false,
      },
      rightPriceScale: {
        visible: true,
        borderVisible: false,
      },
      timeScale: {
        visible: false,
        borderVisible: false,
      },
      handleScroll: false,
      handleScale: false,
      crosshair: {
        vertLine: { color: 'rgba(255, 255, 255, 0.1)' },
        horzLine: { color: 'rgba(255, 255, 255, 0.1)' },
      },
    })

    const priceSeries = chart.addSeries(AreaSeries, {
      lineColor: 'rgba(74, 222, 128, 0.8)',
      topColor: 'rgba(74, 222, 128, 0.18)',
      bottomColor: 'rgba(74, 222, 128, 0.02)',
      lineWidth: 2,
      priceScaleId: 'left',
      priceFormat: {
        type: 'custom',
        formatter: formatAsPercent,
      },
    })

    const reserveSeries = chart.addSeries(LineSeries, {
      color: 'rgba(217, 176, 112, 0.6)',
      lineWidth: 1,
      priceScaleId: 'right',
      priceFormat: {
        type: 'custom',
        formatter: formatAsSats,
      },
    })

    chartRef.current = chart
    priceSeriesRef.current = priceSeries
    reserveSeriesRef.current = reserveSeries

    const observer = new ResizeObserver((entries) => {
      for (const entry of entries) {
        chart.applyOptions({ width: entry.contentRect.width })
      }
    })
    observer.observe(container)

    return () => {
      observer.disconnect()
      chart.remove()
      chartRef.current = null
      priceSeriesRef.current = null
      reserveSeriesRef.current = null
    }
  }, [])

  useEffect(() => {
    if (!priceSeriesRef.current || !reserveSeriesRef.current || !chartRef.current) return
    if (data.length < 2) return

    const priceData = data.map((point) => ({
      time: point.time as UTCTimestamp,
      value: point.priceLong,
    }))

    const reserveData = data.map((point) => ({
      time: point.time as UTCTimestamp,
      value: point.reserve,
    }))

    priceSeriesRef.current.setData(priceData)
    reserveSeriesRef.current.setData(reserveData)
    chartRef.current.timeScale().fitContent()
  }, [data])

  return <div className="price-chart-container" ref={containerRef} />
}
